CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(10) NOT NULL CHECK (role IN ('BUYER','SELLER','ADMIN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);